### ISSUE TITLE
Message Handling

### ISSUE THREAD

**Issue by rallinator7** [platform-eden/courier#9]
# User Story

As a developer, I would like to be able to pull in a go module that will allow my microservices to discover and communicate with one another in an event driven protocol.
 
# Description

Courier is a messaging module written in Go that helps microservices discover and communicate with one another.  Messages that need to be sent to other microservices have a subject that can be subscribed to by services and hold content in a byte array that allows for any formatting that can be marshaled.  Courier allows for plug and play discovery methods through an interface, so it can fit whatever networking configuration developers may need.  These discovery methods simply need to allow for services to post what subjects they subscribe and create, and courier will make sure the messages get to the right place.  Not only can a service subscribe to a thread, Courier can handle multiple goroutines subscribing at a time, which allows for flexible, concurrent services.

# Acceptance Criteria

- [ ] Courier should allow for individual goroutines to subscribe to a subject
- [ ] Courier should allow for any type of marshalable content to be passed between services
- [ ] Courier should be able to pick up changes in the Courier network to make sure all services are getting the correct messages
- [ ] Courier should be able to handle service crashes so one service doesn't impact the productivity of the rest in the system
- [ ] Courier should be able to be secure through TLS
- [ ] Courier should be able to authenticate other services through JWT
